name: TEM-intro-2024
channels:
  - conda-forge
dependencies:
  - hyperspy-base
  - hyperspy-gui-ipywidgets
  - hyperspy-gui-traitsui
  - seaborn
  - pandas
  - tabulate
  - requests
  - ipympl
  - atomap
  - pyxem=0.19.1
  - exspy
  - jupyterlab